language: minimal
sudo: false

env:
  - NAME=alpine-graalvm-1.0.0-rc15 BASE_IMAGE=lustefaniak/docker-graalvm:alpine-1.0.0-rc15.0
  - NAME=alpine-adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jre8u202-b08-alpine 
  - NAME=alpine-adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jre-11.0.2.9-alpine
services:
  - docker

script:
  - bash build.sh
  - bash test.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    tags: true