language: minimal
sudo: false

env:
  - NAME=alpine-graalvm8 BASE_IMAGE=lustefaniak/docker-graalvm:alpine-19.2.0
  - NAME=alpine-adoptopenjdk8 BASE_IMAGE=adoptopenjdk/openjdk8:jre8u222-b10-alpine 
  - NAME=alpine-adoptopenjdk11 BASE_IMAGE=adoptopenjdk/openjdk11:jre-11.0.4_11-alpine
services:
  - docker

script:
  - bash build.sh
  - bash test.sh

deploy:
  provider: script
  script: bash push.sh
  on:
    tags: true